### ISSUE TITLE
Order bug

### ISSUE THREAD

**Issue by BotBw** [AY2122S2-CS2113-T11-4/tp#101]
Dish menu:
1. dish 1
2. dish 2
3. dish 3

<img width="641" alt="image" src="https://user-images.githubusercontent.com/67575050/160832886-52be3433-a8d6-4ad1-b8d6-3f341f075c7e.png">

Dish index start from 1, not 0

<img width="288" alt="image" src="https://user-images.githubusercontent.com/67575050/160832387-de15d647-b29a-445f-a7e5-c6443cc85ff4.png">

null shouldn't be printed in the order

**Comment by wang1351** [comment]
ok
