### ISSUE TITLE
[PE-D] Overly verbose example for add staff

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-T11-4/tp#117]
Perhaps reconsider if it is necessary for so many lines of content?

![image.png](https://raw.githubusercontent.com/shunyao643/ped/main/files/a52fd104-35ad-4cf7-9f6b-49bbdf0f8d28.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: shunyao643/ped#2

**Comment by darylhjd** [comment]
LOL
