### ISSUE TITLE
[PE-D] Printing Receipt bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-T11-4/tp#120]
![image.png](https://raw.githubusercontent.com/striris/ped/main/files/83a3e2f2-cca9-487e-ad3d-e752b979a9a5.png)

When printing the receipt, there is a null in front of the receipt.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: striris/ped#4

**Comment by darylhjd** [comment]
same as #116
