### ISSUE TITLE
[PE-D] Menu-based interface

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-T11-4/tp#123]
The team project expextation states that the application should target users who can type fast and prefer command input. Also, it is recommended to use one-shot commands rather than multi-step commands.
![image.png](https://raw.githubusercontent.com/ElaineQT/ped/main/files/d8ca5ca4-27a5-470b-8145-23540855f5ca.png)
However, this application is menu-based, rather than command-based. Each functionality is designed in a multi-step manner. Is it better to use one-shot commands for interface?

![image.png](https://raw.githubusercontent.com/ElaineQT/ped/main/files/4232564e-bab6-4b48-8a0d-6bf2a5ede833.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ElaineQT/ped#3

**Comment by darylhjd** [comment]
As per new information in user guide, using a menu may actually be faster. up to you guys whether to change or not.

**Comment by wang1351** [comment]
prefer the one we already have :D

**Comment by Lim-Shi-Han** [comment]
I also prefer the menu way:)
