### ISSUE TITLE
[PE-D] Indexing and deletion bug in order menu

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-T11-4/tp#124]
![image.png](https://raw.githubusercontent.com/striris/ped/main/files/b0e87a96-8b4b-4684-b2ea-7de77e793c43.png)

![image.png](https://raw.githubusercontent.com/striris/ped/main/files/c4b78489-27d8-4400-8d4c-4445b8b7c463.png)

Now I realized that the order index actually start from 0. But the first time I try to delete the order 0, the total expense is still 180, the second time I delete the order 0, the total expense displays 0. 
You might want to look into that :)
And it would be better to a) have an option to view all of your orders. b) start the indexing from 1 to make it more convenient for users.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: striris/ped#6

**Comment by darylhjd** [comment]
might be better for user facing index to start from 1, then minus 1 in the backend.

**Comment by wang1351** [comment]
I think they are reviewing a previous version
