### ISSUE TITLE
[PE-D] No orders list

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-T11-4/tp#126]
The application does not allow users to view the list of all orders. As a result, when the user tries to delete an order, get total price of an order, or print receipt of an order, how can the user know the index of the order he/she refers to?

![image.png](https://raw.githubusercontent.com/ElaineQT/ped/main/files/9a52d5fe-1266-4d47-a690-205f31c5bfa3.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: ElaineQT/ped#4

**Comment by darylhjd** [comment]
add option to print all orders.
