### ISSUE TITLE
DG Review

### ISSUE THREAD

**Issue by swongts** [AY2122S2-CS2113-T11-4/tp#141]
1. For your class diagrams, use the standard symbols used for visibility (i.e. -, +, ~) taught in class for the diagrams, don't use non-representative syntax

2. Consider removing numbering for sequence diagram

3. Dotted line should terminate after the cross on some of the objects   - hint: look at how ab3 does it
![image](https://user-images.githubusercontent.com/70316271/161373329-0010d6c3-cdb3-4419-82ed-f18377ad27c3.png)

 4. Some errors in management order
- Self invocation done wrongly for the deleteOrder command 
![image](https://user-images.githubusercontent.com/70316271/161373369-cf102c0c-2d4d-4f51-babf-9d6cff601dfa.png)
 
- deleteOrder command has a class that was not referenced at all 
![image](https://user-images.githubusercontent.com/70316271/161373377-896d3405-bea7-437d-8b79-6a13a5437551.png)
 
- Arrow not pointing to start of activation bar 
![image](https://user-images.githubusercontent.com/70316271/161373400-087b1e4d-8e03-480a-b647-a49cf50ca53c.png)
![image](https://user-images.githubusercontent.com/70316271/161373409-ce51eb2f-69ab-4652-a082-29d8add35af1.png)

5. Many of your methods include its type, visibility and exception thrown, but u can eliminate unnecessary words, and just write the name of the method 
![image](https://user-images.githubusercontent.com/70316271/161373447-f88e4876-0136-4fb7-a8dd-6bf2c0b04126.png)

eg. optionSwitcher(int choice)

**Comment by wang1351** [comment]
ok
