### ISSUE TITLE
Code Review - Daryl

### ISSUE THREAD

**Issue by swongts** [AY2122S2-CS2113-T11-4/tp#144]
**Controller.java**
 
![image](https://user-images.githubusercontent.com/70316271/161412730-01ac5e79-0e20-4778-905a-2db4d5394d1b.png)

Boolean naming doesn’t adhere to standards. 
You could also consider throwing an exception if it goes to the default case.
Another thing to make your code better is to make some of these strings a constant, so that readers can tell whether it is a error message, or welcome message etc.

Good use of spacing that makes your code neat and readable.

**Comment by darylhjd** [comment]
which boolean name?
