### ISSUE TITLE
Code Review - Ziyan

### ISSUE THREAD

**Issue by swongts** [AY2122S2-CS2113-T11-4/tp#146]
**OrderManager.java**
 
![image](https://user-images.githubusercontent.com/70316271/161413041-f9e3881b-7588-4d85-925e-cbac0e09b470.png)

You can extract out each if or else condition as methods and separate each line (such as line 74 and 79), as those are very long and hard to understand

**OrderController.java**
 
![image](https://user-images.githubusercontent.com/70316271/161413047-601ba2fb-20cc-4ffe-aea9-5276cbf48784.png)

You can combine these two try catch blocks since they are catching the same exception.

Overall try to refactor some of your methods to make them shorter and try to do one thing per line instead of combining many methods so that it is easier to understand.

**Comment by wang1351** [comment]
Thank you! I fixed everything except the try catch blocks part. They are in different methods and I did not come up with a good solution to combine.
