### ISSUE TITLE
Database for order

### ISSUE THREAD

**Issue by wang1351** [AY2122S2-CS2113-T11-4/tp#63]

**Comment by darylhjd** [comment]
is this done?

**Comment by wang1351** [comment]
> is this done?

No, this one seems not necessary

**Comment by wang1351** [comment]
> is this done?

i can do tmr

**Comment by darylhjd** [comment]
isnt your ordermanager alr implement the load and store alr? that means should be done alr?

**Comment by wang1351** [comment]
> 

just copied from dishManager, dk whether it works properly, after checking I close this one
