### ISSUE TITLE
Tiny bug when checking valid name

### ISSUE THREAD

**Issue by BotBw** [AY2122S2-CS2113-T11-4/tp#83]
https://github.com/AY2122S2-CS2113-T11-4/tp/blob/963eaa46ec529f85da4c7f4125bb2549cad1e8a0/src/main/java/seedu/duke/entities/Staff.java#L27-L30

Should be 
```java
name.equals("")
```

**Comment by Lim-Shi-Han** [comment]
I've decided to change it to name.length() == 0, I realised dish also has the same problem with the isValidName method so I will change accordingly as well

I will push in the next PR thanks
